belitung/app/Http/routes.php
Route::get('ki-admin/notif-sms/receiver/json',array('as' => 'ki-admin.notif-sms.getReceiverJson','uses' => 'NotifSMSController@getReceiverJson'));
Route::group(['middleware' => 'admin'], function()
{
	Route::get('/admin/dashboard',array('as' => 'ki-admin.dashboard', 'uses' => 'AdminController@getDashboard'));
	Route::get('/admin/logout',array('as' => 'ki-admin.logout', 'uses' => 'AdminController@getLogout'));
	Route::get('/admin/changepassword',array('as' => 'ki-admin.getChangePassword', 'uses' => 'AdminController@getChangePassword'));
	Route::post('/admin/changepassword',array('as' => 'ki-admin.postChangePassword', 'uses' => 'AdminController@postChangePassword'));
	Route::get('/admin/reset-database', array('as' => 'ki-admin.getResetDatabase', 'uses' => 'AdminController@getTruncateDatabase'));
	Route::post('/admin/reset-database', array('as' => 'ki-admin.postResetDatabase', 'uses' => 'AdminController@postTruncateDatabase'));
	Route::get('/admin/refresh-bonus',array('as' => 'ki-admin.refresh-bonus', 'uses' => 'AdminController@refreshBonus'));

	Route::get('ki-admin/attribute/{id}/delete',array('as'=> 'ki-admin.attribute.delete','uses' => 'AttributeController@destroy'));
	Route::resource('ki-admin/attribute', 'AttributeController');

	Route::get('ki-admin/brand/{id}/delete',array('as'=> 'ki-admin.brand.delete','uses' => 'BrandController@destroy'));
	Route::resource('ki-admin/brand', 'BrandController');

	Route::get('ki-admin/categoryproduct/{id}/delete',array('as'=> 'ki-admin.categoryproduct.delete','uses' => 'CategoryProductController@destroy'));
	Route::resource('ki-admin/categoryproduct', 'CategoryProductController');

	Route::get('ki-admin/product/{id}/delete',array('as'=> 'ki-admin.product.delete','uses' => 'ProductController@destroy'));
	Route::get('ki-admin/product/{id}/downloadfile',array('as'=> 'ki-admin.product.downloadfile','uses' => 'ProductController@downloadFile'));
	Route::get('ki-admin/product/{id}/deletefile',array('as'=> 'ki-admin.product.deletefile','uses' => 'ProductController@deleteFile'));
	Route::resource('ki-admin/product', 'ProductController');

	Route::get('ki-admin/stock-product/{id}/delete',array('as'=> 'ki-admin.stock-product.delete','uses' => 'StockProductController@destroy'));
	Route::resource('ki-admin/stock-product', 'StockProductController');	

	Route::get('ki-admin/productimage/{id}/delete',array('as'=> 'ki-admin.productimage.delete','uses' => 'ProductImageController@destroy'));
	Route::resource('ki-admin/productimage', 'ProductImageController');

	Route::get('ki-admin/role/admin/{id}/edit',array('as' => 'ki-admin.role.admin.edit', 'uses' => 'RoleController@editAdmin'));
	Route::put('ki-admin/role/admin/{id}/edit',array('as'  => 'ki-admin.role.admin.update', 'uses' => 'RoleController@updateRoleAdmin'));
	Route::resource('ki-admin/role', 'RoleController');

	Route::get('ki-admin/aktif',array('as'=> 'ki-admin.user.aktif','uses' => 'UserController@aktif'));
		Route::get('ki-admin/silver',array('as'=> 'ki-admin.user.silver','uses' => 'UserController@silver'));
		Route::get('ki-admin/gold',array('as'=> 'ki-admin.user.gold','uses' => 'UserController@gold'));

	Route::get('ki-admin/user/{id}/delete',array('as'=> 'ki-admin.user.delete','uses' => 'UserController@destroy'));
	Route::get('ki-admin/user/{id}/reset',array('as'=> 'ki-admin.user.reset','uses' => 'UserController@reset'));
	Route::resource('ki-admin/user', 'UserController');

	Route::get('ki-admin/detailattribute/{id}/delete',array('as'=> 'ki-admin.detailattribute.delete','uses' => 'DetailAttributeController@destroy'));
	Route::resource('ki-admin/detailattribute', 'DetailAttributeController');

	Route::resource('ki-admin/general','GeneralController');
	Route::get('ki-admin/registrationfee',array('as' => 'ki-admin.registrationfee.index','uses' => 'PointController@registrationFee'));
	Route::get('ki-admin/registrationfee/{id}/edit',array('as' => 'ki-admin.registrationfee.edit','uses' => 'PointController@registrationFeeEdit'));
	Route::put('ki-admin/registrationfee/{id}/edit', array('as' => 'ki-admin.registrationfee.update','uses' => 'PointController@registrationFeeUpdate'));
	Route::post('ki-admin/registrationfee/create', array('as' => 'ki-admin.registrationfee.store','uses' => 'PointController@registrationFeeStore'));
	
	Route::resource('ki-admin/point','PointController');
	Route::resource('ki-admin/referral','ReferralController');

	Route::get('ki-admin/notif-sms/{id}/delete',array('as'=> 'ki-admin.notif-sms.delete','uses' => 'NotifSMSController@destroy'));
	Route::resource('ki-admin/notif-sms', 'NotifSMSController');

	Route::get('ki-admin/notif-email/{id}/delete',array('as'=> 'ki-admin.notif-email.delete','uses' => 'NotifEmailController@destroy'));
	Route::resource('ki-admin/notif-email', 'NotifEmailController');

	Route::get('ki-admin/notification/{id}/delete',array('as'=> 'ki-admin.notification.delete','uses' => 'NotificationController@destroy'));
	Route::resource('ki-admin/notification', 'NotificationController');

	Route::get('ki-admin/chatmobile/{id}/delete',array('as'=> 'ki-admin.chatmobile.delete','uses' => 'ChatMobileController@destroy'));
	Route::post('ki-admin/storeadmin',array('as'=> 'ki-admin.chatmobile.storeadmin','uses' => 'ChatMobileController@storeadmin'));
	Route::resource('ki-admin/chatmobile', 'ChatMobileController');

	Route::get('ki-admin/voicebox/{id}/delete',array('as'=> 'ki-admin.voicebox.delete','uses' => 'VoiceBoxController@destroy'));
	Route::resource('ki-admin/voicebox', 'VoiceBoxController');

	Route::get('ki-admin/notif-message/inbox',array('as'=> 'ki-admin.notif-message.inbox','uses' => 'NotifMessageCustomerController@inbox'));
	Route::get('ki-admin/notif-message/outbox',array('as'=> 'ki-admin.notif-message.outbox','uses' => 'NotifMessageCustomerController@outbox'));
	Route::get('ki-admin/notif-message/customer/delete',array('as'=> 'ki-admin.notif-message.customer.delete','uses' => 'NotifMessageCustomerController@destroy'));
	Route::resource('ki-admin/notif-message/customer', 'NotifMessageCustomerController');
	Route::get('ki-admin/notif-message/employee/delete',array('as'=> 'ki-admin.notif-message.employee.delete','uses' => 'NotifMessageEmployeeController@destroy'));
	Route::resource('ki-admin/notif-message/employee', 'NotifMessageEmployeeController');

	Route::get('ki-admin/contact-us/{id}/delete',array('as'=> 'ki-admin.contact-us.delete','uses' => 'ContactUsController@destroy'));
	Route::resource('ki-admin/contact-us', 'ContactUsController');

	Route::get('ki-admin/report/user', array('as' => 'ki-admin.report.user', 'uses' => 'ReportController@user'));
	Route::get('ki-admin/report/afiliasi', array('as' => 'ki-admin.report.afiliasi', 'uses' => 'ReportController@afiliasi'));
	Route::get('ki-admin/report/sales', array('as' => 'ki-admin.report.sales', 'uses' => 'ReportController@sales'));
	Route::get('ki-admin/report/bonus', array('as' => 'ki-admin.report.bonus', 'uses' => 'ReportController@bonus'));

	Route::get('ki-admin/image/{id}/delete',array('as'=> 'ki-admin.image.delete','uses' => 'ImageController@destroy'));
	Route::resource('ki-admin/image', 'ImageController');

	Route::get('ki-admin/image/{id}/delete',array('as'=> 'ki-admin.image.delete','uses' => 'ImageController@destroy'));
	Route::resource('ki-admin/image', 'ImageController');

	Route::get('ki-admin/category-article/{id}/delete',array('as'=> 'ki-admin.category-article.delete','uses' => 'CategoryArticleController@destroy'));
	Route::resource('ki-admin/category-article', 'CategoryArticleController');

	Route::get('ki-admin/article/{id}/delete',array('as'=> 'ki-admin.article.delete','uses' => 'ArticleController@destroy'));
	Route::resource('ki-admin/article', 'ArticleController');

	Route::get('ki-admin/payment/{payment}/delete',array('as'=> 'ki-admin.payment.delete','uses' => 'PaymentController@destroy'));
	Route::resource('ki-admin/payment','PaymentController');

	Route::get('ki-admin/shippingoffice/{id}/change',array('as'=> 'ki-admin.shippingoffice.change','uses' => 'ShippingOfficeController@change'));
	Route::get('ki-admin/shippingoffice/{shippingoffice}/delete',array('as'=> 'ki-admin.shippingoffice.delete','uses' => 'ShippingOfficeController@destroy'));
	Route::resource('ki-admin/shippingoffice','ShippingOfficeController');

	Route::get('ki-admin/order/{id}/delete',array('as'=> 'ki-admin.order.delete','uses' => 'OrderController@destroy'));
	Route::get('ki-admin/order/{id}/change',array('as'=> 'ki-admin.order.change','uses' => 'OrderController@change'));
	Route::resource('ki-admin/order','OrderController');

	Route::get('ki-admin/transfer/{id}/delete',array('as'=> 'ki-admin.transfer.delete','uses' => 'TransferController@destroy'));
	Route::get('ki-admin/transfer/{id}/change',array('as'=> 'ki-admin.transfer.change','uses' => 'TransferController@change'));
	Route::resource('ki-admin/transfer','TransferController');

	Route::get('ki-admin/permission/{id}/delete',array('as'=> 'ki-admin.permission.delete','uses' => 'ArticleController@destroy'));
	Route::resource('ki-admin/permission','PermissionController');
	Route::get('ki-admin/adminmenu/{id}/delete',array('as'=> 'ki-admin.adminmenu.delete','uses' => 'AdminMenuController@destroy'));
	Route::resource('ki-admin/adminmenu','AdminMenuController');
	Route::get('ki-admin/employee/{id}/delete',array('as'=> 'ki-admin.employee.delete','uses' => 'EmployeeController@destroy'));
	Route::get('ki-admin/employee/{id}/reset',array('as'=> 'ki-admin.employee.reset','uses' => 'EmployeeController@reset'));
	Route::resource('ki-admin/employee','EmployeeController');

	Route::get('ki-admin/notif-registrationfee/{id}/delete',array('as'=> 'ki-admin.notif-registrationfee.delete','uses' => 'RegistrationFeeController@destroy'));
	Route::get('ki-admin/notif-registrationfee/{id}/change',array('as'=> 'ki-admin.notif-registrationfee.change','uses' => 'RegistrationFeeController@change'));
	Route::resource('ki-admin/notif-registrationfee','RegistrationFeeController');
	

belitung/app/DetailAttribute.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Attribute;
use App\DetailAttributeProduct;

class DetailAttribute extends Model {

	protected $table = 'ms_detail_attributes';
	protected $guarded = ['id'];
    public $timestamps = false;

    public function attribute()
    {
    	return $this->belongsTo('App\Attribute', 'ms_attribute_id', 'id');
    }

    public function detailAttributeProducts()
    {
    	return $this->hasMany('App\DetailAttributeProduct', 'ms_detail_attribute_id', 'id');
    }

}

belitung/app/Http/Controllers/DetailAttributeController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use App\DetailAttribute;
use App\Http\Requests\DetailAttributeRequest;
use App\Attribute;

use Session;
class DetailAttributeController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index(DetailAttributeRequest $request)
	{
		$data['ms_attribute_id'] = $request->input('attribute');
		$data['content'] = DetailAttribute::where('ms_attribute_id', '=', $data['ms_attribute_id'])->get();
		return view('pages.detailattribute.index', compact('data'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create(DetailAttributeRequest $request)
	{
		$data['ms_attribute_id'] = $request->input('attribute');
		$data['attribute'] = Attribute::lists('name', 'id');
		return view('pages.detailattribute.create', compact('data'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(DetailAttributeRequest $request)
	{
		DetailAttribute::create($request->all());
		Session::flash('success','Data berhasil ditambahkan');
		return redirect()->route('ki-admin.detailattribute.index', ['attribute' => $request->input('ms_attribute_id')]);
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$data['content'] = DetailAttribute::find($id);
		$data['ms_attribute_id'] = $data['content']->ms_attribute_id;
		return view('pages.detailattribute.edit', compact('data'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update(DetailAttributeRequest $request, $id)
	{
		$data = DetailAttribute::find($id);
		$data->update($request->all());
		Session::flash('success','Data berhasil diperbarui');
		return redirect()->route('ki-admin.detailattribute.index', ['attribute' => $request->input('ms_attribute_id')]);
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$detailAttribute = DetailAttribute::find($id);
		$attribute_id = $detailAttribute->ms_attribute_id;
		foreach ($detailAttribute->detailAttributeProducts as $val) {
			foreach ($val->detailAttributeProductDetailOrders as $vall) {
				$vall->delete();
			}
			$val->delete();
		}
		$detailAttribute->delete();
		Session::flash('success','Data berhasil dihapus');
		return redirect()->route('ki-admin.detailattribute.index', ['attribute' => $attribute_id]);
	}

}

belitung/resources/views/pages/detailattribute/create.blade.php
@extends('layouts.app')

@section('content')
            <section class="content-header">
                    <h1>
                        Dashboard
                        <small>Control panel</small>
                    </h1>
                    <ol class="breadcrumb">
                        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                        <li class="active">Dashboard</li>
                    </ol>
                </section>

                <!-- Main content -->
                <section class="content">

                    <div class="row">
                        <div class="col-xs-12">
                        {!! Form::open(array('route' => 'ki-admin.detailattribute.store', 'method' => 'POST')) !!}
                            @include('pages.detailattribute.form',array('submit' => 'Simpan', 'data' => $data))
                        {!! Form::close() !!}
                        </div>
                    </div>
                </section>
@endsection


@section('custom-head')
    
@endsection

@section('custom-footer')
    
@endsection

belitung/resources/views/pages/detailattribute/edit.blade.php
@extends('layouts.app')

@section('content')
            <section class="content-header">
                    <h1>
                        Dashboard
                        <small>Control panel</small>
                    </h1>
                    <ol class="breadcrumb">
                        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                        <li class="active">Dashboard</li>
                    </ol>
                </section>

                <!-- Main content -->
                <section class="content">

                    <div class="row">
                        <div class="col-xs-12">
                        {!! Form::model($data['content'],array('route' => ['ki-admin.detailattribute.update',$data['content']->id], 'method' => 'PUT')) !!}
                            @include('pages.detailattribute.form',array('submit' => 'Perbarui', 'data' => $data))
                        {!! Form::close() !!}
                        </div>
                    </div>
                </section>
@endsection


@section('custom-head')
    
@endsection

@section('custom-footer')
    
@endsection

belitung/resources/views/pages/detailattribute/form.blade.php
<div class="box-body">
	@if(isset($data['ms_attribute_id']))
		{!! Form::hidden('ms_attribute_id', $data['ms_attribute_id'],array('class' => 'form-control')) !!}
	@endif
	<div class="form-group">
		{!! Form::label('name','Name') !!}
		{!! Form::text('name',null, array('class' => 'form-control')) !!}
	</div>
	<div class="form-group">
		{!! Form::submit($submit, array('class' => 'btn btn-primary')) !!}
	</div>
</div>

belitung/resources/views/pages/detailattribute/index.blade.php
@extends('layouts.app')

@section('content')
            <section class="content-header">
                    <h1>
                        Dashboard
                        <small>Control panel</small>
                    </h1>
                    <ol class="breadcrumb">
                        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                        <li class="active">Dashboard</li>
                    </ol>
                </section>

                <!-- Main content -->
                <section class="content">

                    <div class="row">
                        <div class="col-xs-12">
                            <div class="box">
                                <div class="box-header">
                                    <h3 class="box-title">Detail Attribute Lists &nbsp;&nbsp;&nbsp;
                                    @if(Auth::user()->hasAccess('ki-admin.detailattribute.delete'))
                                        <a href="{!! route('ki-admin.detailattribute.create', ['attribute' => $data['ms_attribute_id']]) !!}" class="btn btn-primary">Tambah Data </a>
                                    @endif
                                    </h3>
                                </div>
                                <div class="box-body table-responsive">
                                    <table id="dataTable" class="table table-bordered table-striped">
                                        <thead>
                                            <tr>
                                                <th>&nbsp;</th>
                                                <th>Value</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($data['content'] as $row)
                                            <tr>
                                                <td>&nbsp;</td>
                                                <td>{{ $row->name }}</td>
                                                <td>
                                                @if(Auth::user()->hasAccess('ki-admin.detailattribute.edit'))
                                                    <a href="{!! route('ki-admin.detailattribute.edit',[$row->id]) !!}" class="fa fa-pencil-square-o"></a>
                                                @endif
                                                @if(Auth::user()->hasAccess('ki-admin.detailattribute.delete'))
                                                    <a href="javascript:void(0);" onclick="deleteModal(this)" data-href="{!! route('ki-admin.detailattribute.delete',[$row->id]) !!}" class="fa fa-trash-o"></a>
                                                @endif
                                                </td>
                                            </tr>
                                            @endforeach
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th>&nbsp;</th>
                                                <th>Value</th>
                                                <th>Action</th>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div><!-- /.box-body -->
                            </div><!-- /.box -->
                            <a href="{!! route('ki-admin.attribute.index') !!}" class="btn-primary">Back</a>
                        </div>
                    </div><!-- /.row (main row) -->

                </section><!-- /.content -->
            @include('scripts.delete-modal')
@endsection


@section('custom-head')
    {!! HTML::style('css/datatables/dataTables.bootstrap.css') !!}
@endsection

@section('custom-footer')
    {!! HTML::script('plugins/datatables/jquery.dataTables.js') !!}
    {!! HTML::script('plugins/datatables/dataTables.bootstrap.js') !!}
    <script type="text/javascript">
        $(function() {
                $('#dataTable').dataTable({
                    "bPaginate": true,
                    "bLengthChange": false,
                    "bFilter": false,
                    "bSort": true,
                    "bInfo": true,
                    "bAutoWidth": false
                });
            });
    </script>
@endsection