belitung/app/Http/routes.php
	Route::get('ki-admin/product/{id}/deletefile',array('as'=> 'ki-admin.product.deletefile','uses' => 'ProductController@deleteFile'));
	Route::resource('ki-admin/product', 'ProductController');

	Route::get('ki-admin/stock-product/{id}/delete',array('as'=> 'ki-admin.stock-product.delete','uses' => 'StockProductController@destroy'));
	Route::resource('ki-admin/stock-product', 'StockProductController');	

	Route::get('ki-admin/productimage/{id}/delete',array('as'=> 'ki-admin.productimage.delete','uses' => 'ProductImageController@destroy'));
	Route::resource('ki-admin/productimage', 'ProductImageController');

	Route::get('ki-admin/role/admin/{id}/edit',array('as' => 'ki-admin.role.admin.edit', 'uses' => 'RoleController@editAdmin'));
	Route::put('ki-admin/role/admin/{id}/edit',array('as'  => 'ki-admin.role.admin.update', 'uses' => 'RoleController@updateRoleAdmin'));
	Route::resource('ki-admin/role', 'RoleController');

	Route::get('ki-admin/aktif',array('as'=> 'ki-admin.user.aktif','uses' => 'UserController@aktif'));
		Route::get('ki-admin/silver',array('as'=> 'ki-admin.user.silver','uses' => 'UserController@silver'));
		Route::get('ki-admin/gold',array('as'=> 'ki-admin.user.gold','uses' => 'UserController@gold'));

	Route::get('ki-admin/user/{id}/delete',array('as'=> 'ki-admin.user.delete','uses' => 'UserController@destroy'));
	Route::get('ki-admin/user/{id}/reset',array('as'=> 'ki-admin.user.reset','uses' => 'UserController@reset'));
	Route::resource('ki-admin/user', 'UserController');

	Route::get('ki-admin/detailattribute/{id}/delete',array('as'=> 'ki-admin.detailattribute.delete','uses' => 'DetailAttributeController@destroy'));
	Route::resource('ki-admin/detailattribute', 'DetailAttributeController');

	Route::resource('ki-admin/general','GeneralController');
	Route::get('ki-admin/registrationfee',array('as' => 'ki-admin.registrationfee.index','uses' => 'PointController@registrationFee'));
	Route::get('ki-admin/registrationfee/{id}/edit',array('as' => 'ki-admin.registrationfee.edit','uses' => 'PointController@registrationFeeEdit'));
	Route::put('ki-admin/registrationfee/{id}/edit', array('as' => 'ki-admin.registrationfee.update','uses' => 'PointController@registrationFeeUpdate'));
	Route::post('ki-admin/registrationfee/create', array('as' => 'ki-admin.registrationfee.store','uses' => 'PointController@registrationFeeStore'));
	
	Route::resource('ki-admin/point','PointController');
	Route::resource('ki-admin/referral','ReferralController');

	Route::get('ki-admin/notif-sms/{id}/delete',array('as'=> 'ki-admin.notif-sms.delete','uses' => 'NotifSMSController@destroy'));
	Route::resource('ki-admin/notif-sms', 'NotifSMSController');

	Route::get('ki-admin/notif-email/{id}/delete',array('as'=> 'ki-admin.notif-email.delete','uses' => 'NotifEmailController@destroy'));
	Route::resource('ki-admin/notif-email', 'NotifEmailController');

	Route::get('ki-admin/notification/{id}/delete',array('as'=> 'ki-admin.notification.delete','uses' => 'NotificationController@destroy'));
	Route::resource('ki-admin/notification', 'NotificationController');

	Route::get('ki-admin/chatmobile/{id}/delete',array('as'=> 'ki-admin.chatmobile.delete','uses' => 'ChatMobileController@destroy'));
	Route::post('ki-admin/storeadmin',array('as'=> 'ki-admin.chatmobile.storeadmin','uses' => 'ChatMobileController@storeadmin'));
	Route::resource('ki-admin/chatmobile', 'ChatMobileController');

	Route::get('ki-admin/voicebox/{id}/delete',array('as'=> 'ki-admin.voicebox.delete','uses' => 'VoiceBoxController@destroy'));
	Route::resource('ki-admin/voicebox', 'VoiceBoxController');

	Route::get('ki-admin/notif-message/inbox',array('as'=> 'ki-admin.notif-message.inbox','uses' => 'NotifMessageCustomerController@inbox'));
	Route::get('ki-admin/notif-message/outbox',array('as'=> 'ki-admin.notif-message.outbox','uses' => 'NotifMessageCustomerController@outbox'));
	Route::get('ki-admin/notif-message/customer/delete',array('as'=> 'ki-admin.notif-message.customer.delete','uses' => 'NotifMessageCustomerController@destroy'));
	Route::resource('ki-admin/notif-message/customer', 'NotifMessageCustomerController');
	Route::get('ki-admin/notif-message/employee/delete',array('as'=> 'ki-admin.notif-message.employee.delete','uses' => 'NotifMessageEmployeeController@destroy'));
	Route::resource('ki-admin/notif-message/employee', 'NotifMessageEmployeeController');

	Route::get('ki-admin/contact-us/{id}/delete',array('as'=> 'ki-admin.contact-us.delete','uses' => 'ContactUsController@destroy'));
	Route::resource('ki-admin/contact-us', 'ContactUsController');

	Route::get('ki-admin/report/user', array('as' => 'ki-admin.report.user', 'uses' => 'ReportController@user'));
	Route::get('ki-admin/report/afiliasi', array('as' => 'ki-admin.report.afiliasi', 'uses' => 'ReportController@afiliasi'));
	Route::get('ki-admin/report/sales', array('as' => 'ki-admin.report.sales', 'uses' => 'ReportController@sales'));
	Route::get('ki-admin/report/bonus', array('as' => 'ki-admin.report.bonus', 'uses' => 'ReportController@bonus'));

	Route::get('ki-admin/image/{id}/delete',array('as'=> 'ki-admin.image.delete','uses' => 'ImageController@destroy'));
	Route::resource('ki-admin/image', 'ImageController');

	Route::get('ki-admin/image/{id}/delete',array('as'=> 'ki-admin.image.delete','uses' => 'ImageController@destroy'));
	Route::resource('ki-admin/image', 'ImageController');

	Route::get('ki-admin/category-article/{id}/delete',array('as'=> 'ki-admin.category-article.delete','uses' => 'CategoryArticleController@destroy'));
	Route::resource('ki-admin/category-article', 'CategoryArticleController');

	Route::get('ki-admin/article/{id}/delete',array('as'=> 'ki-admin.article.delete','uses' => 'ArticleController@destroy'));
	Route::resource('ki-admin/article', 'ArticleController');

	Route::get('ki-admin/payment/{payment}/delete',array('as'=> 'ki-admin.payment.delete','uses' => 'PaymentController@destroy'));
	Route::resource('ki-admin/payment','PaymentController');

	Route::get('ki-admin/shippingoffice/{id}/change',array('as'=> 'ki-admin.shippingoffice.change','uses' => 'ShippingOfficeController@change'));
	Route::get('ki-admin/shippingoffice/{shippingoffice}/delete',array('as'=> 'ki-admin.shippingoffice.delete','uses' => 'ShippingOfficeController@destroy'));
	Route::resource('ki-admin/shippingoffice','ShippingOfficeController');

	Route::get('ki-admin/order/{id}/delete',array('as'=> 'ki-admin.order.delete','uses' => 'OrderController@destroy'));
	Route::get('ki-admin/order/{id}/change',array('as'=> 'ki-admin.order.change','uses' => 'OrderController@change'));
	Route::resource('ki-admin/order','OrderController');

	Route::get('ki-admin/transfer/{id}/delete',array('as'=> 'ki-admin.transfer.delete','uses' => 'TransferController@destroy'));
	Route::get('ki-admin/transfer/{id}/change',array('as'=> 'ki-admin.transfer.change','uses' => 'TransferController@change'));
	Route::resource('ki-admin/transfer','TransferController');

	Route::get('ki-admin/permission/{id}/delete',array('as'=> 'ki-admin.permission.delete','uses' => 'ArticleController@destroy'));
	Route::resource('ki-admin/permission','PermissionController');
	Route::get('ki-admin/adminmenu/{id}/delete',array('as'=> 'ki-admin.adminmenu.delete','uses' => 'AdminMenuController@destroy'));
	Route::resource('ki-admin/adminmenu','AdminMenuController');
	Route::get('ki-admin/employee/{id}/delete',array('as'=> 'ki-admin.employee.delete','uses' => 'EmployeeController@destroy'));
	Route::get('ki-admin/employee/{id}/reset',array('as'=> 'ki-admin.employee.reset','uses' => 'EmployeeController@reset'));
	Route::resource('ki-admin/employee','EmployeeController');

	Route::get('ki-admin/notif-registrationfee/{id}/delete',array('as'=> 'ki-admin.notif-registrationfee.delete','uses' => 'RegistrationFeeController@destroy'));
	Route::get('ki-admin/notif-registrationfee/{id}/change',array('as'=> 'ki-admin.notif-registrationfee.change','uses' => 'RegistrationFeeController@change'));
	Route::resource('ki-admin/notif-registrationfee','RegistrationFeeController');
	
	Route::get('ki-admin/notif-withdraw/{id}/delete',array('as'=> 'ki-admin.notif-withdraw.delete','uses' => 'WithdrawController@destroy'));
	Route::get('ki-admin/notif-withdraw/{id}/change',array('as'=> 'ki-admin.notif-withdraw.change','uses' => 'WithdrawController@change'));
	Route::resource('ki-admin/notif-withdraw','WithdrawController');
	
	Route::get('ki-admin/notif-review/{id}/delete',array('as'=> 'ki-admin.notif-review.delete','uses' => 'ReviewController@destroy'));
	Route::get('ki-admin/notif-review/{id}/change',array('as'=> 'ki-admin.notif-review.change','uses' => 'ReviewController@change'));
	Route::resource('ki-admin/notif-review','ReviewController');

	Route::get('ki-admin/ppn',array('as' => 'ki-admin.ppn.index','uses' => 'PPNController@index'));
});
Route::get('user/role/json',array('as' => 'ki-admin.role.getjson','uses' => 'RoleController@getjson'));
Route::get('chat/getchat/json',array('as' => 'ki-admin.chat.getjson','uses' => 'ChatMobileController@getjson'));

Route::group(['middleware' => 'maintenance'], function()
{	
	Route::get('/', array('as' => 'home', 'uses' => 'PageController@index'));
	Route::get('/products/{category?}', array('as'=> 'product', 'uses' => 'PageController@products'));
	Route::get('/products/detail/{code}/{name?}', array('as' => 'user.product.detail', 'uses' => 'PageController@detailproduct'));
	Route::get('/page/{page}','PageController@page');
	Route::get('/search',array('as' => 'search', 'uses' => 'PageController@search'));
	Route::get('/api/products/getjson', array('as'=> 'product.getjson', 'uses' => 'ProductController@getjson'));

	Route::get('/partner-area',array('as' => 'partner-area','uses' => 'PageController@partner'));
	Route::get('/partner-area/{code}/show',array('as' => 'partner-show','uses' => 'PageController@partnerShow'));

	Route::get('/articles/{code}',array('as' => 'articles', 'uses' => 'PageController@article'));

belitung/app/VoiceBox.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use App\GCM;

class VoiceBox extends Model {

	protected $table = 'tr_voice_boxs';
	protected $guarded = ['id'];
	protected $filled = ['name', 'email', 'telp','title','description','photo','is_anonymous','ms_gcm_id','read_flag'];
	public $timestamps = true;
	public function gcm()
	{
		return $this->belongsTo('App\GCM', 'ms_gcm_id', 'id');
	}


}

belitung/app/Http/Controllers/VoiceBoxController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use Auth;
use Image;
use File;

class VoiceBoxController extends BasicController {
	protected $GCM_API = 'AIzaSyDU78ChBtG2Wl0cdp8GQu567lOEA3EICZU';
	protected $path;
	function __construct() {
		
		$this->path = 'data/voicebox/';

		parent::__construct();
	}
	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$data['content'] = \App\VoiceBox::with('gcm')->get();
		return view('pages.voicebox.index', compact('data'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$data['group'] = array('1' => 'Group');
		$data['receiver'] = \App\User::whereHas('roles', function($q) {
			$q->where('locked', '<>', '1');
		})->lists('email', 'email');
		return view('pages.voicebox.create', compact('data'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(Request $request)
	{

		$inp = array();
		$inp['name'] = $request->input('name');
		$inp['email'] = $request->input('email');
		$inp['telp'] = $request->input('handphone');
		$inp['title'] = $request->input('title');
		$inp['description'] = $request->input('description');
		$inp['is_anonymous'] = $request->input('is_anonymous');
		$inp['read_flag'] = '0';
		$gcm_id = $request->input('gcm_id');
		$gcm = \App\GCM::where('gcm_id', $gcm_id)->first();
		$user_id = $request->input('user_id');
		$anonymous = $inp['is_anonymous'];
		if(empty($gcm)){
			$gcm = new \App\GCM;
			$gcm->gcm_id = $gcm_id;
			
			$gcm->ms_user_id = $user_id;
			$gcm->is_anonymous = $anonymous;
			$gcm->save();
		}else{
			$gcm->gcm_id = $gcm_id;
			$gcm->ms_user_id = $user_id;
			$gcm->is_anonymous = $anonymous;
			$gcm->save();
		}
		$photo = $request->input('photo');

		if(!empty($photo))
		{

			$photo = urldecode($photo);
			$decoded=base64_decode($photo);
			$filename = "_voicebox_".date('Ymd_Hsi').'.JPEG';

			file_put_contents($this->path.$filename,$decoded);

			$inp['photo']  = $filename;		
			
		}
		
		$inp['ms_gcm_id'] = $gcm->id;
		$vb = \App\VoiceBox::create($inp);
		$json = array();
		$json['RESP'] = "SCSVCBX";
		$json['MESSAGE'] = 'Kotak suara berhasil terkirim.';
		$json['DATA'] = $vb->toArray();
		return json_encode($json);
	}

	public function storetwo(Request $request)
	{

		$inp = array();
		$inp['name'] = $request->input('name');
		$inp['email'] = $request->input('email');
		$inp['telp'] = $request->input('handphone');
		$inp['title'] = $request->input('title');
		$inp['description'] = $request->input('description');
		$inp['is_anonymous'] = $request->input('is_anonymous');
		$gcm_id = $request->input('gcm_id');
		$gcm = \App\GCM::where('gcm_id', $gcm_id)->first();
		$user_id = $request->input('user_id');
		$anonymous = $inp['is_anonymous'];
		if(empty($gcm)){
			$gcm = new \App\GCM;
			$gcm->gcm_id = $gcm_id;
			
			$gcm->ms_user_id = $user_id;
			$gcm->is_anonymous = $anonymous;
			$gcm->save();
		}else{
			$gcm->gcm_id = $gcm_id;
			$gcm->ms_user_id = $user_id;
			$gcm->is_anonymous = $anonymous;
			$gcm->save();
		}
		// $photo = $request->input('photo');
		if ($request->hasFile('photo'))
		{
		    $file = $request->file('photo');
			$extension = $file->getClientOriginalExtension();
			$fileName = "_voicebox_".date('Ymd_Hsi').'.'.$extension;
			$file->move($this->path,$fileName);
			$img = Image::make($this->path.$fileName);
			$img->save($this->path.$fileName, 60);
			$inp['photo']= $fileName;
		}
	
		// if(!empty($photo))
		// {

		// 	$photo = urldecode($photo);
		// 	$decoded=base64_decode($photo);
		// 	$filename = "_voicebox_".date('Ymd_Hsi').'.JPEG';

		// 	file_put_contents($this->path.$filename,$decoded);

		// 	$inp['photo']  = $filename;		
			
		// }
		// var_dump("Sdfas");exit();
		$inp['ms_gcm_id'] = $gcm->id;
		$vb = \App\VoiceBox::create($inp);
		$json = array();
		$json['RESP'] = "SCSVCBX";
		$json['MESSAGE'] = 'Kotak suara berhasil terkirim.';
		$json['DATA'] = $vb->toArray();
		return json_encode($json);
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$data['content'] = \App\VoiceBox::find($id);
		$data['content']->read_flag = '1';
		$data['content']->save();
		return view('pages.voicebox.show', compact('data'));
	}
	public function destroy($id)
	{
		$data = \App\VoiceBox::find($id);
		if(File::exists($this->path.$data->photo))
			File::delete($this->path.$data->photo);
		\App\VoiceBox::destroy($id);
		return redirect()->route('ki-admin.voicebox.index');
	}

	protected function sendNotif($data)
	{
		if(Mail::send('theme.'.$this->theme->code.'.include.voicebox',$data, function($message) use($data)
		{
			$message->subject($data['subject']);
			$message->to($data['receiver']);
		})) {
			return true;
		}
		else {
			return false;
		}
	}

	public function getReceiverJson()
	{
		$tipe = Input::get('tipe');
		if($tipe == '0') {
			$receiver = User::whereHas('roles', function($q) {
							$q->where('locked', '<>', '1');
						})->get();
		}
		else if($tipe == '1') {
			$receiver = Role::where('locked', '<>', '1')->get();
		}
		return response()->json($receiver);
	}
}

belitung/resources/views/pages/voicebox/create.blade.php
@extends('layouts.app')

@section('content')
<section class="content-header">
  <h1>
    Notification
    <small>Mobile</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Dashboard</li>
  </ol>
</section>

<!-- Main content -->
<section class="content">

  <div class="row">
    <div class="col-md-3">
      <a href="{!! route('ki-admin.notification.index') !!}" class="btn btn-primary btn-block margin-bottom">Back to Sent Folder</a>
      <div class="box box-solid">
        <div class="box-header with-border">
          <h3 class="box-title">Folders</h3>
        </div>
        <div class="box-body no-padding">
          <ul class="nav nav-pills nav-stacked">
            <li><a href="{!! route('ki-admin.notification.index') !!}"><i class="fa fa-envelope-o"></i> Sent</a></li>
          </ul>
        </div><!-- /.box-body -->
      </div><!-- /. box -->
    </div><!-- /.col -->
    <div class="col-md-9" >
      {!! Form::open(array('route' => 'ki-admin.notification.store', 'method' => 'POST', 'files' => true)) !!}
      @include('pages.notification.form',array('submit' => 'Send'))
      {!! Form::close() !!}
    </div>
  </div>
</section>

@endsection


@section('custom-head')
{!! HTML::style('theme/keiskei/plugin/selectize/css/selectize.css') !!}
{!! HTML::style('theme/keiskei/plugin/selectize/css/selectize.bootstrap3.css') !!}
@endsection

@section('custom-footer')
{!! HTML::script('theme/keiskei/plugin/selectize/js/standalone/selectize.js') !!}
<script type="text/javascript">
  $(document).ready(function() {
   $('#receiver').selectize();
   var changeReceiverSelectFunc = (function changeReceiverSelect(){

      var tipe = $('#group').val();
      changeReceiver(tipe);

      return changeReceiverSelect; //return the function itself to reference

  }()); 
   $('#group').change(function() {
    changeReceiverSelectFunc();
  });
 });
  $(function () {
    var tipe = $('#group').val();
    changeReceiver(tipe);
  });
  function changeReceiver(x)
  {
    $.get("{!! route('ki-admin.notif-email.getReceiverJson') !!}", {tipe : x}, function(data, status) {
      if(status == 'success') {
        var content = [];
        var temp = {'text' : "Semua", 'value' : 0};
        content.push(temp);
        $.each(data, function(key, value) {
          var temp = {'text' : value.name, 'value' : value.id};
          content.push(temp);
        });
        console.log(content);
        var selectize = $("#receiver")[0].selectize;
        selectize.clear();
        selectize.clearOptions();
        selectize.load(function(callback) {
          callback(content);
        });
      }
    });
  };
</script>
@endsection

belitung/resources/views/pages/voicebox/edit.blade.php
@extends('layouts.app')

@section('content')
            <section class="content-header">
                    <h1>
                        Dashboard
                        <small>Control panel</small>
                    </h1>
                    <ol class="breadcrumb">
                        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                        <li class="active">Dashboard</li>
                    </ol>
                </section>

                <!-- Main content -->
                <section class="content">

                    <div class="row">
                        <div class="col-xs-12">
                        {!! Form::model($data['content'],array('route' => ['ki-admin.brand.update',$data['content']->id], 'method' => 'PUT')) !!}
                            @include('pages.brand.form',array('submit' => 'Perbarui'))
                        {!! Form::close() !!}
                        </div>
                    </div>
                </section>
@endsection


@section('custom-head')
    
@endsection

@section('custom-footer')
    
@endsection

belitung/resources/views/pages/voicebox/form.blade.php
<div class="col-md-12">
	<div class="box box-primary">
		<div class="box-header with-border">
			<h3 class="box-title">Compose New Message</h3>
		</div><!-- /.box-header -->
		<div class="box-body">
			<div class="form-group">
				{!! Form::label('group', 'Tipe') !!}
				{!! Form::select('group', $data['group'], null, array('class' => 'form-control')) !!}
			</div>
			<div class="form-group">
				{!! Form::label('receiver', 'To') !!}
				{!! Form::select('receiver', $data['receiver'], null, array('class' => 'form-control')) !!}
			</div>
			<div class="form-group">
				{!! Form::label('title', 'Title') !!}
				{!! Form::text('title', null, array('class' => 'form-control', 'placeholder' => 'Subject:')) !!}
			</div>
			<div class="form-group">
				{!! Form::label('photo', 'Image') !!}
				{!! Form::file('photo') !!}
			</div>
			<div class="form-group">
				{!! Form::label('description', 'Description') !!}
				{!! Form::textarea('description', null, array('class' => 'form-control', 'placeholder' => 'Description ...')) !!}
			</div>
		</div><!-- /.box-body -->
		<div class="box-footer">
			<div class="pull-right">
				<button type="submit" class="btn btn-primary"><i class="fa fa-envelope-o"></i> Send</button>
			</div>
			<a href="{!! route('ki-admin.notification.index') !!}" class="btn btn-default"><i class="fa fa-times"></i> Discard</a>
		</div><!-- /.box-footer -->
	</div><!-- /. box -->
</div><!-- /.col -->

belitung/resources/views/pages/voicebox/index.blade.php
@extends('layouts.app')

@section('content')
<section class="content-header">
        <h1>
            Kotak Suara
            <small>Mobile</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Dashboard</li>
        </ol>
    </section>

<!-- Main content -->
<section class="content">

    <div class="row">
        <div class="col-md-12">
          <div class="box">
            <div class="box-header with-border">
              <h3 class="box-title">Kotak Suara</h3>
              @if(Auth::user()->hasAccess('ki-admin.voicebox.index'))
              &nbsp;&nbsp;&nbsp;<a href="{!! route('ki-admin.voicebox.index') !!}" class="btn btn-primary btn-sm">Refresh</a>
              @endif
            </div><!-- /.box-header -->
            <div class="box-body table-responsive">
              <table id="dataTable" class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Title</th>
                    <th>Email</th>
                    <th>Timestamp</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach($data['content'] as $row)
                    <tr>
                      <td>{!! $row->name !!}</td>
                      <td><a href="{!! route('ki-admin.voicebox.show', [$row->id]) !!}">{!! $row->read_flag == '1'?$row->title:'<b>'.$row->title.'</b>' !!}</a></td>
                      <td>{!! $row->email !!}</td>
                      <td>{!! $row->created_at !!}</td>
                      <td>
                          <a href="javascript:void(0);" onclick="deleteModal(this)" data-href="{!! route('ki-admin.voicebox.delete',[$row->id]) !!}" class="fa fa-trash-o"></a>
                      </td>
                    </tr>
                  @endforeach
                </tbody>
                <tfoot>
                  <tr>
                    <th>Name</th>
                    <th>Title</th>
                    <th>Email</th>
                    <th>Timestamp</th>
                    <th>Action</th>
                  </tr>
                </tfoot>
              </table>
            </div><!-- /.box-body -->
          </div><!-- /.box -->
        </div>
    </div>
</section>
@include('scripts.delete-modal')
@endsection


@section('custom-head')
{!! HTML::style('css/datatables/dataTables.bootstrap.css') !!}
@endsection

@section('custom-footer')
{!! HTML::script('plugins/datatables/jquery.dataTables.js') !!}
{!! HTML::script('plugins/datatables/dataTables.bootstrap.js') !!}
<script type="text/javascript">
  $(function() {
    $('#dataTable').dataTable();
  });
</script>
@endsection

belitung/resources/views/pages/voicebox/show.blade.php
@extends('layouts.app')

@section('content')
<section class="content-header">
        <h1>
            Kotak Suara
            <small>mobile</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Dashboard</li>
        </ol>
    </section>

<!-- Main content -->
<section class="content">
    <div class="row">
            <div class="col-md-12">
              <div class="box box-primary">
                <div class="box-header with-border">
                  <h3 class="box-title">Detail Kotak Suara</h3>
                </div><!-- /.box-header -->
                <div class="box-body no-padding">
                  <div class="mailbox-read-info">
                    <h3>Title : {!! $data['content']->title !!}</h3>
                    <h5>Name: {!! $data['content']->name !!} <span class="mailbox-read-time pull-right">{!! $data['content']->created_at !!}</span></h5>
                    <h5>Email: {!! $data['content']->email !!}</h5>
                    <h5>Telp: {!! $data['content']->telp !!}</h5>
                  </div><!-- /.mailbox-read-info -->
                  <div class="mailbox-read-message">
                    <h4>Pesan :</h4>
                    {!! $data['content']->description !!}
                  </div><!-- /.mailbox-read-message -->
                </div><!-- /.box-body -->
                <div class="box-footer">
                <div class="row">
                  <div class="col-md-4">
                    Image :
                  </div>
                  <div class="col-md-8">
                    @if(File::exists('ws/data/voicebox/'.$data['content']->photo))
                          <a href="{!! asset('ws/data/voicebox/'.$data['content']->photo) !!}" target="_blank" class="btn btn-primary btn-sm">Download</a>
                        @else
                          Not uploaded.
                        @endif
                  </div>
                </div>
                
                
                </div><!-- /.box-footer -->
              </div><!-- /. box -->
            </div><!-- /.col -->
    </div>

    <div class="row">
        <div class="col-md-3">
          <a href="{!! route('ki-admin.voicebox.index') !!}" class="btn btn-warning btn-block margin-bottom">Back</a>
        </div>
    </div>
    </section>
@endsection


@section('custom-head')
{!! HTML::style('css/datatables/dataTables.bootstrap.css') !!}
@endsection

@section('custom-footer')
{!! HTML::script('plugins/datatables/jquery.dataTables.js') !!}
{!! HTML::script('plugins/datatables/dataTables.bootstrap.js') !!}
<script type="text/javascript">
  $(function() {
    $('#dataTable').dataTable();
  });
</script>
@endsection