belitung/app/Http/routes.php
	Route::get('ki-admin/product/{id}/delete',array('as'=> 'ki-admin.product.delete','uses' => 'ProductController@destroy'));
	Route::get('ki-admin/product/{id}/downloadfile',array('as'=> 'ki-admin.product.downloadfile','uses' => 'ProductController@downloadFile'));
	Route::get('ki-admin/product/{id}/deletefile',array('as'=> 'ki-admin.product.deletefile','uses' => 'ProductController@deleteFile'));
	Route::resource('ki-admin/product', 'ProductController');

	Route::get('ki-admin/stock-product/{id}/delete',array('as'=> 'ki-admin.stock-product.delete','uses' => 'StockProductController@destroy'));
	Route::resource('ki-admin/stock-product', 'StockProductController');	

	Route::get('ki-admin/productimage/{id}/delete',array('as'=> 'ki-admin.productimage.delete','uses' => 'ProductImageController@destroy'));
	Route::resource('ki-admin/productimage', 'ProductImageController');

	Route::get('ki-admin/role/admin/{id}/edit',array('as' => 'ki-admin.role.admin.edit', 'uses' => 'RoleController@editAdmin'));
	Route::put('ki-admin/role/admin/{id}/edit',array('as'  => 'ki-admin.role.admin.update', 'uses' => 'RoleController@updateRoleAdmin'));
	Route::resource('ki-admin/role', 'RoleController');

	Route::get('ki-admin/aktif',array('as'=> 'ki-admin.user.aktif','uses' => 'UserController@aktif'));
		Route::get('ki-admin/silver',array('as'=> 'ki-admin.user.silver','uses' => 'UserController@silver'));
		Route::get('ki-admin/gold',array('as'=> 'ki-admin.user.gold','uses' => 'UserController@gold'));

	Route::get('ki-admin/user/{id}/delete',array('as'=> 'ki-admin.user.delete','uses' => 'UserController@destroy'));
	Route::get('ki-admin/user/{id}/reset',array('as'=> 'ki-admin.user.reset','uses' => 'UserController@reset'));
	Route::resource('ki-admin/user', 'UserController');

	Route::get('ki-admin/detailattribute/{id}/delete',array('as'=> 'ki-admin.detailattribute.delete','uses' => 'DetailAttributeController@destroy'));
	Route::resource('ki-admin/detailattribute', 'DetailAttributeController');

	Route::resource('ki-admin/general','GeneralController');
	Route::get('ki-admin/registrationfee',array('as' => 'ki-admin.registrationfee.index','uses' => 'PointController@registrationFee'));
	Route::get('ki-admin/registrationfee/{id}/edit',array('as' => 'ki-admin.registrationfee.edit','uses' => 'PointController@registrationFeeEdit'));
	Route::put('ki-admin/registrationfee/{id}/edit', array('as' => 'ki-admin.registrationfee.update','uses' => 'PointController@registrationFeeUpdate'));
	Route::post('ki-admin/registrationfee/create', array('as' => 'ki-admin.registrationfee.store','uses' => 'PointController@registrationFeeStore'));
	
	Route::resource('ki-admin/point','PointController');
	Route::resource('ki-admin/referral','ReferralController');

	Route::get('ki-admin/notif-sms/{id}/delete',array('as'=> 'ki-admin.notif-sms.delete','uses' => 'NotifSMSController@destroy'));
	Route::resource('ki-admin/notif-sms', 'NotifSMSController');

	Route::get('ki-admin/notif-email/{id}/delete',array('as'=> 'ki-admin.notif-email.delete','uses' => 'NotifEmailController@destroy'));
	Route::resource('ki-admin/notif-email', 'NotifEmailController');

	Route::get('ki-admin/notification/{id}/delete',array('as'=> 'ki-admin.notification.delete','uses' => 'NotificationController@destroy'));
	Route::resource('ki-admin/notification', 'NotificationController');

	Route::get('ki-admin/chatmobile/{id}/delete',array('as'=> 'ki-admin.chatmobile.delete','uses' => 'ChatMobileController@destroy'));
	Route::post('ki-admin/storeadmin',array('as'=> 'ki-admin.chatmobile.storeadmin','uses' => 'ChatMobileController@storeadmin'));
	Route::resource('ki-admin/chatmobile', 'ChatMobileController');

	Route::get('ki-admin/voicebox/{id}/delete',array('as'=> 'ki-admin.voicebox.delete','uses' => 'VoiceBoxController@destroy'));
	Route::resource('ki-admin/voicebox', 'VoiceBoxController');

	Route::get('ki-admin/notif-message/inbox',array('as'=> 'ki-admin.notif-message.inbox','uses' => 'NotifMessageCustomerController@inbox'));
	Route::get('ki-admin/notif-message/outbox',array('as'=> 'ki-admin.notif-message.outbox','uses' => 'NotifMessageCustomerController@outbox'));
	Route::get('ki-admin/notif-message/customer/delete',array('as'=> 'ki-admin.notif-message.customer.delete','uses' => 'NotifMessageCustomerController@destroy'));
	Route::resource('ki-admin/notif-message/customer', 'NotifMessageCustomerController');
	Route::get('ki-admin/notif-message/employee/delete',array('as'=> 'ki-admin.notif-message.employee.delete','uses' => 'NotifMessageEmployeeController@destroy'));
	Route::resource('ki-admin/notif-message/employee', 'NotifMessageEmployeeController');

	Route::get('ki-admin/contact-us/{id}/delete',array('as'=> 'ki-admin.contact-us.delete','uses' => 'ContactUsController@destroy'));
	Route::resource('ki-admin/contact-us', 'ContactUsController');

	Route::get('ki-admin/report/user', array('as' => 'ki-admin.report.user', 'uses' => 'ReportController@user'));
	Route::get('ki-admin/report/afiliasi', array('as' => 'ki-admin.report.afiliasi', 'uses' => 'ReportController@afiliasi'));
	Route::get('ki-admin/report/sales', array('as' => 'ki-admin.report.sales', 'uses' => 'ReportController@sales'));
	Route::get('ki-admin/report/bonus', array('as' => 'ki-admin.report.bonus', 'uses' => 'ReportController@bonus'));

	Route::get('ki-admin/image/{id}/delete',array('as'=> 'ki-admin.image.delete','uses' => 'ImageController@destroy'));
	Route::resource('ki-admin/image', 'ImageController');

	Route::get('ki-admin/image/{id}/delete',array('as'=> 'ki-admin.image.delete','uses' => 'ImageController@destroy'));
	Route::resource('ki-admin/image', 'ImageController');

	Route::get('ki-admin/category-article/{id}/delete',array('as'=> 'ki-admin.category-article.delete','uses' => 'CategoryArticleController@destroy'));
	Route::resource('ki-admin/category-article', 'CategoryArticleController');

	Route::get('ki-admin/article/{id}/delete',array('as'=> 'ki-admin.article.delete','uses' => 'ArticleController@destroy'));
	Route::resource('ki-admin/article', 'ArticleController');

	Route::get('ki-admin/payment/{payment}/delete',array('as'=> 'ki-admin.payment.delete','uses' => 'PaymentController@destroy'));
	Route::resource('ki-admin/payment','PaymentController');

	Route::get('ki-admin/shippingoffice/{id}/change',array('as'=> 'ki-admin.shippingoffice.change','uses' => 'ShippingOfficeController@change'));
	Route::get('ki-admin/shippingoffice/{shippingoffice}/delete',array('as'=> 'ki-admin.shippingoffice.delete','uses' => 'ShippingOfficeController@destroy'));
	Route::resource('ki-admin/shippingoffice','ShippingOfficeController');

	Route::get('ki-admin/order/{id}/delete',array('as'=> 'ki-admin.order.delete','uses' => 'OrderController@destroy'));
	Route::get('ki-admin/order/{id}/change',array('as'=> 'ki-admin.order.change','uses' => 'OrderController@change'));
	Route::resource('ki-admin/order','OrderController');

	Route::get('ki-admin/transfer/{id}/delete',array('as'=> 'ki-admin.transfer.delete','uses' => 'TransferController@destroy'));
	Route::get('ki-admin/transfer/{id}/change',array('as'=> 'ki-admin.transfer.change','uses' => 'TransferController@change'));
	Route::resource('ki-admin/transfer','TransferController');

	Route::get('ki-admin/permission/{id}/delete',array('as'=> 'ki-admin.permission.delete','uses' => 'ArticleController@destroy'));
	Route::resource('ki-admin/permission','PermissionController');
	Route::get('ki-admin/adminmenu/{id}/delete',array('as'=> 'ki-admin.adminmenu.delete','uses' => 'AdminMenuController@destroy'));
	Route::resource('ki-admin/adminmenu','AdminMenuController');
	Route::get('ki-admin/employee/{id}/delete',array('as'=> 'ki-admin.employee.delete','uses' => 'EmployeeController@destroy'));
	Route::get('ki-admin/employee/{id}/reset',array('as'=> 'ki-admin.employee.reset','uses' => 'EmployeeController@reset'));
	Route::resource('ki-admin/employee','EmployeeController');

	Route::get('ki-admin/notif-registrationfee/{id}/delete',array('as'=> 'ki-admin.notif-registrationfee.delete','uses' => 'RegistrationFeeController@destroy'));
	Route::get('ki-admin/notif-registrationfee/{id}/change',array('as'=> 'ki-admin.notif-registrationfee.change','uses' => 'RegistrationFeeController@change'));
	Route::resource('ki-admin/notif-registrationfee','RegistrationFeeController');
	
	Route::get('ki-admin/notif-withdraw/{id}/delete',array('as'=> 'ki-admin.notif-withdraw.delete','uses' => 'WithdrawController@destroy'));
	Route::get('ki-admin/notif-withdraw/{id}/change',array('as'=> 'ki-admin.notif-withdraw.change','uses' => 'WithdrawController@change'));
	Route::resource('ki-admin/notif-withdraw','WithdrawController');
	
	Route::get('ki-admin/notif-review/{id}/delete',array('as'=> 'ki-admin.notif-review.delete','uses' => 'ReviewController@destroy'));
	Route::get('ki-admin/notif-review/{id}/change',array('as'=> 'ki-admin.notif-review.change','uses' => 'ReviewController@change'));
	Route::resource('ki-admin/notif-review','ReviewController');

	Route::get('ki-admin/ppn',array('as' => 'ki-admin.ppn.index','uses' => 'PPNController@index'));
});
Route::get('user/role/json',array('as' => 'ki-admin.role.getjson','uses' => 'RoleController@getjson'));
Route::get('chat/getchat/json',array('as' => 'ki-admin.chat.getjson','uses' => 'ChatMobileController@getjson'));

Route::group(['middleware' => 'maintenance'], function()
{	
	Route::get('/', array('as' => 'home', 'uses' => 'PageController@index'));
	Route::get('/products/{category?}', array('as'=> 'product', 'uses' => 'PageController@products'));
	Route::get('/products/detail/{code}/{name?}', array('as' => 'user.product.detail', 'uses' => 'PageController@detailproduct'));
	Route::get('/page/{page}','PageController@page');
	Route::get('/search',array('as' => 'search', 'uses' => 'PageController@search'));
	Route::get('/api/products/getjson', array('as'=> 'product.getjson', 'uses' => 'ProductController@getjson'));

	Route::get('/partner-area',array('as' => 'partner-area','uses' => 'PageController@partner'));

belitung/app/ChatMobile.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use App\GCM;
use App\User;

class ChatMobile extends Model {

	protected $table = 'tr_chats';
	protected $guarded = ['id'];
	protected $filled = ['name','email','handphone','description', 'photo', 'ms_gcm_id','parent','read_flag','is_admin','ms_user_admin_id','path_user'];
	public $timestamps = true;
	public function gcm()
	{
		return $this->belongsTo('App\GCM', 'ms_gcm_id', 'id');
	}
	public function admin()
	{
		return $this->belongsTo('App\User', 'ms_user_admin_id', 'id');
	}


}

belitung/resources/views/pages/chatmobile/create.blade.php
@extends('layouts.app')

@section('content')
<section class="content-header">
  <h1>
    Notification
    <small>Mobile</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Dashboard</li>
  </ol>
</section>

<!-- Main content -->
<section class="content">

  <div class="row">
    <div class="col-md-3">
      <a href="{!! route('ki-admin.notification.index') !!}" class="btn btn-primary btn-block margin-bottom">Back to Sent Folder</a>
      <div class="box box-solid">
        <div class="box-header with-border">
          <h3 class="box-title">Folders</h3>
        </div>
        <div class="box-body no-padding">
          <ul class="nav nav-pills nav-stacked">
            <li><a href="{!! route('ki-admin.notification.index') !!}"><i class="fa fa-envelope-o"></i> Sent</a></li>
          </ul>
        </div><!-- /.box-body -->
      </div><!-- /. box -->
    </div><!-- /.col -->
    <div class="col-md-9" >
      {!! Form::open(array('route' => 'ki-admin.notification.store', 'method' => 'POST', 'files' => true)) !!}
      @include('pages.notification.form',array('submit' => 'Send'))
      {!! Form::close() !!}
    </div>
  </div>
</section>

@endsection


@section('custom-head')
{!! HTML::style('theme/keiskei/plugin/selectize/css/selectize.css') !!}
{!! HTML::style('theme/keiskei/plugin/selectize/css/selectize.bootstrap3.css') !!}
@endsection

@section('custom-footer')
{!! HTML::script('theme/keiskei/plugin/selectize/js/standalone/selectize.js') !!}
<script type="text/javascript">
  $(document).ready(function() {
   $('#receiver').selectize();
   var changeReceiverSelectFunc = (function changeReceiverSelect(){

      var tipe = $('#group').val();
      changeReceiver(tipe);

      return changeReceiverSelect; //return the function itself to reference

  }()); 
   $('#group').change(function() {
    changeReceiverSelectFunc();
  });
 });
  $(function () {
    var tipe = $('#group').val();
    changeReceiver(tipe);
  });
  function changeReceiver(x)
  {
    $.get("{!! route('ki-admin.notif-email.getReceiverJson') !!}", {tipe : x}, function(data, status) {
      if(status == 'success') {
        var content = [];
        var temp = {'text' : "Semua", 'value' : 0};
        content.push(temp);
        $.each(data, function(key, value) {
          var temp = {'text' : value.name, 'value' : value.id};
          content.push(temp);
        });
        console.log(content);
        var selectize = $("#receiver")[0].selectize;
        selectize.clear();
        selectize.clearOptions();
        selectize.load(function(callback) {
          callback(content);
        });
      }
    });
  };
</script>
@endsection

belitung/resources/views/pages/chatmobile/edit.blade.php
@extends('layouts.app')

@section('content')
            <section class="content-header">
                    <h1>
                        Dashboard
                        <small>Control panel</small>
                    </h1>
                    <ol class="breadcrumb">
                        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                        <li class="active">Dashboard</li>
                    </ol>
                </section>

                <!-- Main content -->
                <section class="content">

                    <div class="row">
                        <div class="col-xs-12">
                        {!! Form::model($data['content'],array('route' => ['ki-admin.brand.update',$data['content']->id], 'method' => 'PUT')) !!}
                            @include('pages.brand.form',array('submit' => 'Perbarui'))
                        {!! Form::close() !!}
                        </div>
                    </div>
                </section>
@endsection


@section('custom-head')
    
@endsection

@section('custom-footer')
    
@endsection

belitung/resources/views/pages/chatmobile/form.blade.php
		<div class="box-body">
			<div class="form-group">
				{!! Form::label('description', 'Description') !!}
				{!! Form::text('description', null, array('class' => 'form-control', 'placeholder' => 'Reply ...')) !!}
				{!! Form::hidden('ms_gcm_id', $data['gcm_id']) !!}
			</div>
			<div class="form-group">
				{!! Form::label('photo', 'Image') !!}
				{!! Form::file('photo') !!}
			</div>
			
		</div><!-- /.box-body -->
		<div class="box-footer">
			<div class="pull-right">
				<button type="submit" class="btn btn-primary"><i class="fa fa-envelope-o"></i> Send</button>
			</div>
			<a href="{!! route('ki-admin.chatmobile.index') !!}" class="btn btn-default"><i class="fa fa-times"></i> Discard</a>
		</div><!-- /.box-footer -->

belitung/resources/views/pages/chatmobile/index.blade.php
@extends('layouts.app')

@section('content')
<section class="content-header">
        <h1>
            Chat Mobile
            <small>Mobile</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Dashboard</li>
        </ol>
    </section>
<!-- Main content -->
<section class="content">

    <div class="row">
        <div class="col-md-12">
          <div class="box">
            <div class="box-header with-border">
              <h3 class="box-title">Inbox</h3>
              @if(Auth::user()->hasAccess('ki-admin.chatmobile.index'))
              &nbsp;&nbsp;&nbsp;<a href="{!! route('ki-admin.chatmobile.index') !!}" class="btn btn-primary btn-sm">Refresh</a>
              @endif
            </div><!-- /.box-header -->
            <div class="box-body table-responsive">
              <table id="dataTable" class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Timestamps</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach($data['content'] as $row)
                    <tr>
                      <td>{!! $row->is_admin == '1'?$row->admin->name:$row->name !!}</td>
                      <td><a href="{!! route('ki-admin.chatmobile.show', [$row->ms_gcm_id]) !!}">
                      @if(in_array($row->ms_gcm_id, $data['list_unread']))
                      <b>  {!! substr($row->description,0,80)."..." !!}</b>
                      @else
                      {!! substr($row->description,0,80)."..." !!}
                      @endif
                      </a></td>
                      <td>{!! $row->created_at !!}</td>
                      <td>
                          <a href="javascript:void(0);" onclick="deleteModal(this)" data-href="{!! route('ki-admin.chatmobile.delete',[$row->ms_gcm_id]) !!}" class="fa fa-trash-o"></a>
                      </td>
                    </tr>
                  @endforeach
                </tbody>
                <tfoot>
                  <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Timestamps</th>
                    <th>Action</th>
                  </tr>
                </tfoot>
              </table>
            </div><!-- /.box-body -->
          </div><!-- /.box -->
        </div>
    </div>
</section>
@include('scripts.delete-modal')
@endsection


@section('custom-head')
{!! HTML::style('css/datatables/dataTables.bootstrap.css') !!}
@endsection

@section('custom-footer')
{!! HTML::script('plugins/datatables/jquery.dataTables.js') !!}
{!! HTML::script('plugins/datatables/dataTables.bootstrap.js') !!}
<script type="text/javascript">
  $(function() {
    $('#dataTable').dataTable();
  });
</script>
@endsection

belitung/resources/views/pages/chatmobile/show.blade.php
@extends('layouts.app')

@section('content')
<section class="content-header">
        <h1>
            Chat Support
            <small>Mobile</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Dashboard</li>
        </ol>
    </section>

<!-- Main content -->
<section class="content">
    <div class="row">
            <div class="col-md-12">
              <div class="box box-primary">
              <div class="box box-warning direct-chat direct-chat-warning">
                <div class="box-header with-border">
                  <h3 class="box-title">Chatt Support</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                  <div class="direct-chat-messages" style="height:450px">
                  @foreach($data['content'] as $row)
                  @if($row->is_admin != '1')
                    <div class="direct-chat-msg">
                      <div class="direct-chat-info clearfix">
                        <span class="direct-chat-name pull-left">
                        @if($row->gcm->is_anonymous == '1')
                        {!! $row->name !!}
                        @else
                        {!! $row->gcm->user->name !!}
                        @endif
                        </span>
                        <span class="direct-chat-timestamp pull-right">{!! $row->created_at !!}</span>
                      </div>
                      <!-- /.direct-chat-info -->
                      <img class="direct-chat-img" src="@if($row->gcm->is_anonymous == '1')
                        https://www.keiskei.co.id/data/im_user.png
                        @else
                        @if(File::exists('ws/data/user/photo/'.$row->gcm->user->photo) and !empty($row->gcm->user->photo))
                        https://www.keiskei.co.id/ws/data/user/photo/{!! $row->gcm->user->photo !!}
                        @else
                        https://www.keiskei.co.id/data/im_user.png
                        @endif
                      
                        @endif" alt="message user image">
                      <div class="direct-chat-text">
                        @if(!empty($row->description))
                          <p>{!! $row->description !!}</p>
                        @endif
                        @if(!empty($row->photo))
                        <p>
                          @if(File::exists('ws/data/chat_mobile/'.$row->photo))
                          <a href="{!! asset('ws/data/chat_mobile/'.$row->photo) !!}" target="_blank" class="btn btn-primary btn-sm">Download</a>
                          @endif
                        </p>
                    @endif
                      </div>
                      <!-- /.direct-chat-text -->
                    </div>
                  @else
                  <div class="direct-chat-msg right">
                      <div class="direct-chat-info clearfix">
                        <span class="direct-chat-name pull-right">{!! $row->admin->name !!}</span>
                        <span class="direct-chat-timestamp pull-left">{!! $row->created_at !!}</span>
                      </div>
                      <!-- /.direct-chat-info -->
                      <img class="direct-chat-img" src="https://www.keiskei.co.id/img/avatar5.png" alt="message user image"><!-- /.direct-chat-img -->
                      <div class="direct-chat-text">
                        @if(!empty($row->description))
                          <p>{!! $row->description !!}</p>
                        @endif
                        @if(!empty($row->photo))
                        <p>
                          @if(File::exists('wdata/chat_mobile/'.$row->photo))
                          <a href="{!! asset('data/chat_mobile/'.$row->photo) !!}" target="_blank" class="btn btn-primary btn-sm">Download</a>
                          @endif
                        </p>
                    @endif
                      </div>
                      <!-- /.direct-chat-text -->
                    </div>
                  @endif
                  @endforeach
                </div><!-- /.box-body -->
                <div class="box-footer">

                  {!! Form::open(array('route' => 'ki-admin.chatmobile.storeadmin', 'method' => 'POST', 'files' => true)) !!}
                  @include('pages.chatmobile.form',array('submit' => 'Send'))
                  {!! Form::close() !!}
                </div><!-- /.box-footer -->
              </div><!-- /. box -->
            </div><!-- /.col -->
    </div>
</section>
@endsection


@section('custom-head')
{!! HTML::style('css/datatables/dataTables.bootstrap.css') !!}
@endsection

@section('custom-footer')
{!! HTML::script('plugins/datatables/jquery.dataTables.js') !!}
{!! HTML::script('plugins/datatables/dataTables.bootstrap.js') !!}
<script type="text/javascript">
  $(function() {
    $('#dataTable').dataTable();
    setInterval("chatRealtime()", 3000);
  });
  $(".direct-chat-messages").animate({ scrollTop: $(document).height() }, "fast");
  function chatRealtime(){
  	$.ajax({
  			url:"{{ url('chat/getchat/json') }}",
			type:"GET",
			data:{
				gcm_id : '{!! $data['gcm_id'] !!}'
			}
		}).done(function(data, status){
			if(status=='success')
			{	
				console.log(data);
				if(jQuery.isEmptyObject(data))
				{
					
				}else
				{
					var html = '';
					var ind = 0;
					$.each(data, function(key, value)
					{

						if(value.is_admin == '1'){
							html += "<div class='direct-chat-msg right'><div class='direct-chat-info clearfix'><span class='direct-chat-name pull-right'>" + value.admin.name +"</span><span class='direct-chat-timestamp pull-left'>"+ value.created_at +"</span></div>                      <img class='direct-chat-img' src='https://www.keiskei.co.id/img/avatar5.png' alt='message user image'><div class='direct-chat-text'>" + value.description ;
                        if(value.photo != ""){
							html += "<a href='https://www.keiskei.co.id/data/chat_mobile/'" + value.photo + " target='_blank' class='btn btn-primary btn-sm'>Download</a>";
                        }
                    	html += "</div></div>";
                      ind++;
						}else{
              ind++;
							html += "<div class='direct-chat-msg'><div class='direct-chat-info clearfix'><span class='direct-chat-name pull-left'>";
							if(value.gcm.is_anonymous == '1'){
								html += value.name;
							}else{
								html += value.gcm.user.name;
							}
							html += "</span><span class='direct-chat-timestamp pull-right'>" + value.created_at + "</span></div>";
							if(value.gcm.is_anonymous == '1'){
								html += "<img class='direct-chat-img' src='https://www.keiskei.co.id/data/im_user.png'  alt='message user image' />";
							}else{
								html += "<img class='direct-chat-img' src='https://www.keiskei.co.id/data/user/photo/" + value.gcm.user.photo + "'  alt='message user image' />";
							}
							html += "<div class='direct-chat-text'> <p>" + value.description + "</p>";
							if(value.photo != ""){
								html += "<a href='https://www.keiskei.co.id/ws/data/chat_mobile/'" + value.photo + "' target='_blank' class='btn btn-primary btn-sm'>Download</a>";
                        	}
                        	html += "</div></div>";
						}

					});
					
					if(ind > 0)
					{
						$('.direct-chat-messages').append(html);
            $(".direct-chat-messages").animate({ scrollTop: $(document).height() }, "fast");
						// $.playSound('<?php echo asset('assets/qcare') ?>');
					}
					console.log(html);
				}
			}
		});
  }
  
</script>
@endsection