belitung/app/Http/routes.php
	Route::post('ki-admin/storeadmin',array('as'=> 'ki-admin.chatmobile.storeadmin','uses' => 'ChatMobileController@storeadmin'));
	Route::resource('ki-admin/chatmobile', 'ChatMobileController');

	Route::get('ki-admin/voicebox/{id}/delete',array('as'=> 'ki-admin.voicebox.delete','uses' => 'VoiceBoxController@destroy'));
	Route::resource('ki-admin/voicebox', 'VoiceBoxController');

	Route::get('ki-admin/notif-message/inbox',array('as'=> 'ki-admin.notif-message.inbox','uses' => 'NotifMessageCustomerController@inbox'));
	Route::get('ki-admin/notif-message/outbox',array('as'=> 'ki-admin.notif-message.outbox','uses' => 'NotifMessageCustomerController@outbox'));
	Route::get('ki-admin/notif-message/customer/delete',array('as'=> 'ki-admin.notif-message.customer.delete','uses' => 'NotifMessageCustomerController@destroy'));
	Route::resource('ki-admin/notif-message/customer', 'NotifMessageCustomerController');
	Route::get('ki-admin/notif-message/employee/delete',array('as'=> 'ki-admin.notif-message.employee.delete','uses' => 'NotifMessageEmployeeController@destroy'));
	Route::resource('ki-admin/notif-message/employee', 'NotifMessageEmployeeController');

	Route::get('ki-admin/contact-us/{id}/delete',array('as'=> 'ki-admin.contact-us.delete','uses' => 'ContactUsController@destroy'));
	Route::resource('ki-admin/contact-us', 'ContactUsController');

	Route::get('ki-admin/report/user', array('as' => 'ki-admin.report.user', 'uses' => 'ReportController@user'));
	Route::get('ki-admin/report/afiliasi', array('as' => 'ki-admin.report.afiliasi', 'uses' => 'ReportController@afiliasi'));
	Route::get('ki-admin/report/sales', array('as' => 'ki-admin.report.sales', 'uses' => 'ReportController@sales'));
	Route::get('ki-admin/report/bonus', array('as' => 'ki-admin.report.bonus', 'uses' => 'ReportController@bonus'));

	Route::get('ki-admin/image/{id}/delete',array('as'=> 'ki-admin.image.delete','uses' => 'ImageController@destroy'));
	Route::resource('ki-admin/image', 'ImageController');

	Route::get('ki-admin/image/{id}/delete',array('as'=> 'ki-admin.image.delete','uses' => 'ImageController@destroy'));
	Route::resource('ki-admin/image', 'ImageController');

	Route::get('ki-admin/category-article/{id}/delete',array('as'=> 'ki-admin.category-article.delete','uses' => 'CategoryArticleController@destroy'));
	Route::resource('ki-admin/category-article', 'CategoryArticleController');

	Route::get('ki-admin/article/{id}/delete',array('as'=> 'ki-admin.article.delete','uses' => 'ArticleController@destroy'));
	Route::resource('ki-admin/article', 'ArticleController');

	Route::get('ki-admin/payment/{payment}/delete',array('as'=> 'ki-admin.payment.delete','uses' => 'PaymentController@destroy'));
	Route::resource('ki-admin/payment','PaymentController');

	Route::get('ki-admin/shippingoffice/{id}/change',array('as'=> 'ki-admin.shippingoffice.change','uses' => 'ShippingOfficeController@change'));
	Route::get('ki-admin/shippingoffice/{shippingoffice}/delete',array('as'=> 'ki-admin.shippingoffice.delete','uses' => 'ShippingOfficeController@destroy'));
	Route::resource('ki-admin/shippingoffice','ShippingOfficeController');

	Route::get('ki-admin/order/{id}/delete',array('as'=> 'ki-admin.order.delete','uses' => 'OrderController@destroy'));
	Route::get('ki-admin/order/{id}/change',array('as'=> 'ki-admin.order.change','uses' => 'OrderController@change'));
	Route::resource('ki-admin/order','OrderController');

	Route::get('ki-admin/transfer/{id}/delete',array('as'=> 'ki-admin.transfer.delete','uses' => 'TransferController@destroy'));
	Route::get('ki-admin/transfer/{id}/change',array('as'=> 'ki-admin.transfer.change','uses' => 'TransferController@change'));
	Route::resource('ki-admin/transfer','TransferController');

	Route::get('ki-admin/permission/{id}/delete',array('as'=> 'ki-admin.permission.delete','uses' => 'ArticleController@destroy'));
	Route::resource('ki-admin/permission','PermissionController');
	Route::get('ki-admin/adminmenu/{id}/delete',array('as'=> 'ki-admin.adminmenu.delete','uses' => 'AdminMenuController@destroy'));
	Route::resource('ki-admin/adminmenu','AdminMenuController');
	Route::get('ki-admin/employee/{id}/delete',array('as'=> 'ki-admin.employee.delete','uses' => 'EmployeeController@destroy'));
	Route::get('ki-admin/employee/{id}/reset',array('as'=> 'ki-admin.employee.reset','uses' => 'EmployeeController@reset'));
	Route::resource('ki-admin/employee','EmployeeController');

	Route::get('ki-admin/notif-registrationfee/{id}/delete',array('as'=> 'ki-admin.notif-registrationfee.delete','uses' => 'RegistrationFeeController@destroy'));
	Route::get('ki-admin/notif-registrationfee/{id}/change',array('as'=> 'ki-admin.notif-registrationfee.change','uses' => 'RegistrationFeeController@change'));
	Route::resource('ki-admin/notif-registrationfee','RegistrationFeeController');
	
	Route::get('ki-admin/notif-withdraw/{id}/delete',array('as'=> 'ki-admin.notif-withdraw.delete','uses' => 'WithdrawController@destroy'));
	Route::get('ki-admin/notif-withdraw/{id}/change',array('as'=> 'ki-admin.notif-withdraw.change','uses' => 'WithdrawController@change'));
	Route::resource('ki-admin/notif-withdraw','WithdrawController');
	
	Route::get('ki-admin/notif-review/{id}/delete',array('as'=> 'ki-admin.notif-review.delete','uses' => 'ReviewController@destroy'));
	Route::get('ki-admin/notif-review/{id}/change',array('as'=> 'ki-admin.notif-review.change','uses' => 'ReviewController@change'));
	Route::resource('ki-admin/notif-review','ReviewController');

	Route::get('ki-admin/ppn',array('as' => 'ki-admin.ppn.index','uses' => 'PPNController@index'));
});
Route::get('user/role/json',array('as' => 'ki-admin.role.getjson','uses' => 'RoleController@getjson'));
Route::get('chat/getchat/json',array('as' => 'ki-admin.chat.getjson','uses' => 'ChatMobileController@getjson'));

Route::group(['middleware' => 'maintenance'], function()
{	
	Route::get('/', array('as' => 'home', 'uses' => 'PageController@index'));
	Route::get('/products/{category?}', array('as'=> 'product', 'uses' => 'PageController@products'));
	Route::get('/products/detail/{code}/{name?}', array('as' => 'user.product.detail', 'uses' => 'PageController@detailproduct'));
	Route::get('/page/{page}','PageController@page');
	Route::get('/search',array('as' => 'search', 'uses' => 'PageController@search'));
	Route::get('/api/products/getjson', array('as'=> 'product.getjson', 'uses' => 'ProductController@getjson'));

	Route::get('/partner-area',array('as' => 'partner-area','uses' => 'PageController@partner'));
	Route::get('/partner-area/{code}/show',array('as' => 'partner-show','uses' => 'PageController@partnerShow'));

	Route::get('/articles/{code}',array('as' => 'articles', 'uses' => 'PageController@article'));
	Route::get('/contact-us', array('as' => 'contact-us', 'uses' => 'PageController@contact'));
	Route::post('/contact-us', array('as' => 'contact-us.store', 'uses' => 'PageController@contactPost'));
	// User / Guest Route
	Route::get('login',array('as' => 'login', 'uses' => 'UserController@getLogin'));
	Route::post('login',array('as' => 'login.store', 'uses' => 'UserController@postLogin'));

	Route::get('register',array('as' => 'register', 'uses' => 'UserController@getRegister'));
	Route::post('register',array('as' => 'register.store', 'uses' => 'UserController@postRegister'));
	Route::post('front-register',array('as' => 'register.front.store', 'uses' => 'UserController@postRegisterDepan'));
	Route::get('user/activate/{token}',array('as' => 'register.activate', 'uses' => 'UserController@getActivate'));
	Route::group(['middleware' => 'customer'], function()
	{
		Route::get('logout',array('as' => 'user.logout', 'uses' => 'UserController@logout'));
		Route::get('user/dashboard',array('as' => 'user.dashboard', 'uses' => 'UserController@dashboard'));
		Route::get('user/profil',array('as' => 'user.profil','uses' => 'UserController@dashboard')) ;

		Route::get('user/verified',array('as' => 'user.verified', 'uses' => 'UserController@verified'));
		Route::put('user/verified',array('as' => 'user.verified.update', 'uses' => 'UserController@verifiedUpdate'));
		Route::get('user/registration/fee',array('as' => 'user.registrationfee','uses' => 'RegistrationFeeController@userCreate'));
		Route::post('user/registration/fee',array('as' => 'user.registrationfee.store','uses' => 'RegistrationFeeController@userStore'));

		Route::get('user/profile/edit',array('as' => 'user.profile.edit', 'uses' => 'UserController@profileEdit'));
		Route::put('user/profile/edit',array('as' => 'user.profile.update', 'uses' => 'UserController@profileUpdate'));
		Route::get('user/status', array('as' => 'user.status', 'uses' => 'LogActivityController@indexUser'));
		Route::get('user/affiliate', array('as' => 'user.affiliate', 'uses' => 'UserController@affiliateUser'));
		Route::get('user/withdraw', array('as' => 'user.withdraw', 'uses' => 'WithdrawController@indexUser'));
		Route::get('user/withdraw/get', array('as' => 'user.withdraw.get', 'uses' => 'WithdrawController@getUser'));

		Route::get('user/cart',array('as' => 'user.cart', 'uses' => 'CartController@indexUser'));
		Route::post('user/cart/{id}', array('as' => 'user.cart.store', 'uses' => 'CartController@store'));
		Route::post('user/cart/{id}/change-total', array('as' => 'user.cart.change-total', 'uses' => 'CartController@changeTotal'));
		Route::get('user/cart/{id}/delete', array('as' => 'user.cart.delete', 'uses' => 'CartController@deleteDetail'));
		Route::get('user/cart/{id}/reseller', array('as' => 'user.cart.reseller', 'uses' => 'CartController@checkReseller'));
		Route::get('user/cart/checkout/agent', array('as' => 'user.cart.checkout.agent', 'uses' => 'CartController@checkoutAgent'));
		Route::get('user/cart/checkout/overseas', array('as' => 'user.cart.checkout.overseas', 'uses' => 'CartController@checkoutOverseas'));
		Route::get('user/report',array('as' => 'user.report', 'uses' => 'ReportController@userIndex'));

belitung/app/Transfer.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Order;
use App\Payment;
use App\User;

class Transfer extends Model {

	protected $table = 'tr_transfers';
	protected $guarded = ['id'];
	protected $fillable = [
		'ms_payment_id',
		'ms_user_id',
		'tr_order_id',
		'custom',
		'nominal',
		'account_name',
		'account_number',
		'status',
		'information',
		'file',
		'transfer_date'
	];

	public function order()
	{
		return $this->belongsTo('App\Order', 'tr_order_id', 'id');
	}

	public function payment()
	{
		return $this->belongsTo('App\Payment', 'ms_payment_id', 'id');
	}

	public function user()
	{
		return $this->belongsTo('App\User', 'ms_user_id', 'id');
	}

}

belitung/app/Http/Controllers/TransferController.php
<?php namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Http\Requests\TransferRequest;
use Auth;
use Illuminate\Http\Request;
use Image;
use Session;
use Input;

use App\Transfer;

class TransferController extends BasicController {

	protected $path;

	function __construct() {
		$this->path = 'data/user/transfer/';
		parent::__construct();
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$type = Input::get('state');
		if(empty($type))
		{
			$type = '0';
			$data['content'] = Transfer::where('status',$type)->orWhere('status',null)->orderBy('created_at','desc')->get();
		}
		else
			$data['content'] = Transfer::where('status',$type)->orderBy('created_at','desc')->get();
		// dd($data);
		return view('pages.transfer.index', compact('data'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create($id)
	{
		$data['order'] = \App\Order::find($id);
		if($data['order']->ms_status_order_id != '2' || $data['order']->ms_user_id != Auth::id())
			return redirect()->route('home');
		$data['payment'] = \App\Payment::all();
		return view('theme.'.$this->theme->code.'.pages.user.transfer',compact('data'));	
	}

	public function store(TransferRequest $request, $id)
	{
		$order = \App\Order::find($id);
		$order->ms_payment_id = $request->input('ms_payment_id');
		$order->save();
		$data = \App\Transfer::create($request->all());
		$data->ms_user_id = Auth::id();
		$data->tr_order_id = $id;
		if ($request->hasFile('file'))
		{
		    $file = $request->file('file');
			$extension = $file->getClientOriginalExtension();
			$fileName = Auth::user()->code."_transfer_".date('Ymd_Hsi').'.'.$extension;
			$file->move($this->path,$fileName);
			$img = Image::make($this->path.$fileName);
			$img->save($this->path.$fileName, 60);
			$data->file = $fileName;
		}
		$data->save();
		Session::flash('success','Pembayaran berhasil ditambahkan. Silahkan Menunggu konfirmasi Admin KEISKEI');
		\App\LogActivity::create([
			'ms_user_id' => Auth::id(),
			'description' => 'User '.Auth::user()->username.' telah melakukan pembayaran Invoice '. $order->code.'. Silahkan Menunggu konfirmasi Admin KEISKEI.'
		]);
		return redirect()->route('user.report');
	}
	public function change($id = null)
	{
		$status = Input::get('state');
		if(empty($id) || empty($status))
			exit();
		$data = Transfer::find($id);
		$data->status = $status;
		if($status == '1')
		{
			\App\LogActivity::create([
				'ms_user_id' => $data->ms_user_id,
				'description' => 'Administrator telah menyetujui konfirmasi pembayaran Anda'
			]);	
			$user = \App\User::find($data->ms_user_id);
			$sms['content'] = '[KEISKEI.CO.ID]~'.'Administrator telah menyetujui konfirmasi pembayaran Anda. Terima Kasih.';
			$sms['receiver'] = $user->mobile;
			$this->sendNotif($sms);		
		}
		$data->save();
		return redirect()->route('ki-admin.transfer.index');
	}
	public function destroy($id)
	{
		$data = Transfer::find($id);
		if(File::exists($this->path.$data->file))
			File::delete($this->path.$data->file);
		$data->delete();
		return redirect()->route('ki-admin.transfer.index');
	}
	public function show($id = '1')
	{
		$data['content'] = Transfer::with('user','user.roles','payment')->find($id);
		return view('pages.transfer.show', compact('data'));
	}
}

belitung/resources/views/pages/transfer/form.blade.php
@extends('layouts.app')

@section('content')
            <section class="content-header">
                    <h1>
                        Dashboard
                        <small>Control panel</small>
                    </h1>
                    <ol class="breadcrumb">
                        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                        <li class="active">Dashboard</li>
                    </ol>
                </section>

                <!-- Main content -->
                <section class="content">

                    <div class="row">
                        <div class="col-xs-12">
                        @if($data['content']->point()->count() > 0)
                        {!! Form::model($data['content']->point,array('route' => ['ki-admin.registrationfee.update',$data['content']->point->id], 'method' => 'PUT')) !!}
                        @else
                        {!! Form::open(array('route' => 'ki-admin.registrationfee.store', 'method' => 'POST')) !!}
                        @endif
                            <div class="box-body">
                                <div class="form-group">
                                    {!! Form::label('role','Role') !!}
                                    {!! Form::text('role',$data['content']->name,array('class'=>'form-control', 'disabled' => 'true')) !!}
                                </div>
                                {!! Form::hidden('ms_role_id',$data['content']->id) !!}
                                <div class="form-group {!! $errors->any()?($errors->first('registrationfee')?' has-error':''):'' !!}">
                                    {!! Form::label('registrationfee','Registration Fee') !!}
                                    <div class="input-group">
                                        <span class="input-group-addon">Rp.</span>
                                        {!! Form::text('registrationfee',null,array('class'=>'form-control')) !!}
                                    </div>
                                    <span class="help-block">{!! $errors->any()?($errors->first('registrationfee')?$errors->first('registrationfee'):''):'' !!}</span>
                                </div>
                                
                               
                                <div class="form-group">
                                {!! BootstrapForm::submit('Simpan') !!}
                                </div>
                            </div>
                        {!! Form::close() !!}
                        </div>
                    </div>
                </section>
@endsection


@section('custom-head')
    
@endsection

@section('custom-footer')
    
@endsection

belitung/resources/views/pages/transfer/index.blade.php
@extends('layouts.app')

@section('content')
            <section class="content-header">
                    <h1>
                        Dashboard
                        <small>Control panel</small>
                    </h1>
                    <ol class="breadcrumb">
                        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                        <li class="active">Dashboard</li>
                    </ol>
                </section>

                <!-- Main content -->
                <section class="content">

                    <div class="row">
                        <div class="col-md-2">
                          @include('pages.transfer.menu')
                        </div><!-- /.col -->
                        <div class="col-md-10">
                            <div class="box">
                                <div class="box-header">
                                    <h3 class="box-title">Transfer Lists &nbsp;&nbsp;&nbsp;</h3>
                                </div>
                                <div class="box-body table-responsive">
                                    <table id="dataTable" class="table table-bordered table-striped">
                                        <thead>
                                            <tr>
                                                <th>Kustomer</th>
                                                <th>Nominal</th>
                                                <th>Pembayaran</th>
                                                <th style="width:150px">Keterangan</th>
                                                <th style="width:130px">Aksi</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($data['content'] as $row)
                                            <tr>
                                                <td>
                                                    <a href="{!! route('ki-admin.transfer.show', [$row->id]) !!}">
                                                        {{ $row->user->name }}
                                                    </a>
                                                </td>
                                                <td>Rp. {{ $row->nominal  }}</td>
                                                <td>{!! $row->payment->name.' '.$row->payment->account_number.' - a/n '.$row->payment->account_name !!}</td>
                                                <td>
                                                <b>{{ $row->account_name }}</b>
                                                <br>
                                                {{ $row->account_number }}
                                                <br>
                                                {!! date('j F Y', strtotime($row->transfer_date)) !!}
                                                <br>
                                                {!! !empty($row->status)?($row->status==1?"<span class='label label-primary'>Approved</span>":"<span class='label label-default'>Disapproved</span>"):"<span class='label label-warning'>Pending</span>" !!}
                                                </td>
                                                <td>
                                                @if(Auth::user()->hasAccess('ki-admin.transfer.change') || Auth::user()->hasAccess('ki-admin.transfer.delete'))
                                                <div class="btn-group">
                                                  <button class="btn btn-danger" type="button">Change</button>
                                                  <button data-toggle="dropdown" class="btn btn-danger dropdown-toggle" type="button">
                                                    <span class="caret"></span>
                                                    <span class="sr-only">Toggle Dropdown</span>
                                                  </button>
                                                  <ul role="menu" class="dropdown-menu">
                                                  @if(Auth::user()->hasAccess('ki-admin.transfer.change'))
                                                    <li><a href="{!! route('ki-admin.transfer.change',[$row->id]).'?state=1' !!}">Approve</a></li>
                                                    <li><a href="{!! route('ki-admin.transfer.change',[$row->id]).'?state=2' !!}">Unapprove</a></li>
                                                  @endif
                                                    <li class="divider"></li>
                                                    @if(Auth::user()->hasAccess('ki-admin.transfer.delete'))
                                                    <li><a href="javascript:void(0);" onclick="deleteModal(this)" data-href="{!! route('ki-admin.transfer.delete',[$row->id]) !!}">Delete</a></li>
                                                    @endif
                                                  </ul>
                                                </div>
                                              @endif
                                                </td>
                                            </tr>
                                            @endforeach
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th>Kustomer</th>
                                                <th>Nominal</th>
                                                <th>Pembayaran</th>
                                                <th>Keterangan</th>
                                                <th>Aksi</th>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div><!-- /.box-body -->
                            </div><!-- /.box -->
                        </div>
                    </div><!-- /.row (main row) -->

                </section><!-- /.content -->
@include('scripts.delete-modal')
@endsection


@section('custom-head')
    {!! HTML::style('css/datatables/dataTables.bootstrap.css') !!}
@endsection

@section('custom-footer')
    {!! HTML::script('plugins/datatables/jquery.dataTables.js') !!}
    {!! HTML::script('plugins/datatables/dataTables.bootstrap.js') !!}
    <script type="text/javascript">
        $(function() {
                $('#dataTable').dataTable({
                    "bPaginate": true,
                    "bLengthChange": false,
                    "bFilter": false,
                    "bSort": true,
                    "bInfo": true,
                    "bAutoWidth": false
                });
            });
    </script>
@endsection

belitung/resources/views/pages/transfer/menu.blade.php
          <div class="box box-solid">
            <div class="box-header with-border">
              <h3 class="box-title">Folders</h3>
            </div>
            <div class="box-body no-padding">
              <ul class="nav nav-pills nav-stacked">
                <li><a href="{!! route('ki-admin.transfer.index').'?status=pending&state=0' !!}"><i class="fa fa-credit-card"></i> Pending</a></li>
                <li><a href="{!! route('ki-admin.transfer.index').'?status=approved&state=1' !!}"><i class="fa fa-credit-card"></i> Approved</a></li>
                <li><a href="{!! route('ki-admin.transfer.index').'?status=unnaproved&state=2' !!}"><i class="fa fa-credit-card"></i> Unnaproved</a></li>
              </ul>
            </div><!-- /.box-body -->
          </div><!-- /. box -->

belitung/resources/views/pages/transfer/show.blade.php
@extends('layouts.app')

@section('content')
<section class="content-header">
        <h1>
            Notification
            <small>Transfer</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Dashboard</li>
        </ol>
    </section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-3">
          
          @include('pages.transfer.menu')
        </div><!-- /.col -->
            <div class="col-md-9">
              <div class="box box-primary">
                <div class="box-header with-border">
                  <h3 class="box-title">Show Detail</h3>
                </div><!-- /.box-header -->
                <div class="box-body no-padding">
                  <div class="mailbox-read-info">
                    <h3>Customer : {!! $data['content']->user->name !!}</h3>
                    <h4>Role : {!! $data['content']->user->roles->first()->name !!} </h4>
                    <h5>Status : {!! $data['content']->status=='1'?"<span class='label label-primary'>Approved</span>":($data['content']->status=='2'?"<span class='label label-danger'>Unnaproved</span>":"<span class='label label-warning'>Pending</span>") !!} </h5>

                  </div><!-- /.mailbox-read-info -->
                  <div class="mailbox-read-message">
                    <h4>Transfer Detail :</h4>
                    <table class="table">
                      <tr>
                        <td>Account Name</td>
                        <td>:</td>
                        <td>{!! $data['content']->account_name !!}</td>
                      </tr>
                      <tr>
                        <td>Account Number</td>
                        <td>:</td>
                        <td>{!! $data['content']->account_number !!}</td>
                      </tr>
                      <tr>
                        <td>Nominal</td>
                        <td>:</td>
                        <td>{!! $data['content']->nominal !!}</td>
                      </tr>
                      <tr>
                        <td>Transfer Date</td>
                        <td>:</td>
                        <td>{!! date('d-m-Y',strtotime($data['content']->transfer_date)) !!}</td>
                      </tr>
                      <tr>
                        <td>File</td>
                        <td>:</td>
                        <td>
                        @if(File::exists('data/user/transfer/'.$data['content']->file) && !empty($data['content']->file))
                          <a href="{!! asset('data/user/transfer/'.$data['content']->file) !!}" target="_blank" class="btn btn-primary btn-sm">Download</a>
                        @else
                          Not uploaded.
                        @endif

                        </td>
                      </tr>
                      <tr>
                        <td>Catatan</td>
                        <td>:</td>
                        <td>{!! $data['content']->information !!}</td>
                      </tr>
                    </table>
                  </div><!-- /.mailbox-read-message -->
                </div><!-- /.box-body -->
                <div class="box-footer">
                </div><!-- /.box-footer -->
                <div class="box-footer">
                </div><!-- /.box-footer -->
              </div><!-- /. box -->
            </div><!-- /.col -->
    </div>
</section>
@endsection


@section('custom-head')
{!! HTML::style('css/datatables/dataTables.bootstrap.css') !!}
@endsection

@section('custom-footer')
{!! HTML::script('plugins/datatables/jquery.dataTables.js') !!}
{!! HTML::script('plugins/datatables/dataTables.bootstrap.js') !!}
<script type="text/javascript">
  $(function() {
    $('#dataTable').dataTable();
  });
</script>
@endsection